### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by olimart** [olimart/yamail#1] opened 2015-02-12 19:28 UTC
**This app will do 2 things:**
- Store email addresses list
- Send email campaigns

**Need to Integrate with Mandrill service:**
- Each user must be able to integrate provider accounts:
  - For now, only Mandrill but
  - Make it as service as I'd like to potentially use other service providers
  - So we need user to authenticate. Check out the docs, I know they provide keys, but maybe there support OAuth as well.

**Features**

- Ability to schedule sending at a future date (Mandrill only support immediate delivery so we need to handle scheduler)
  - Schedule sending with sidekiq
- Sending action requires:
  - A list of email addresses (either full list or segment only)
  - Message: user must be able to paste template (with variables). We'll keep it simple (not our fault if email is screwed).

- After campaign sent we need to take screenshot of email
- Need to capture campaign status from provider:
  - Campaign scheduled/sent/canceled...
- Need to capture basic info about campaign: 
  - 100 sent, 3, bounced back...

**Comment by croko** [comment] 2015-02-23 10:54
> Ability to schedule sending at a future date (Mandrill only support immediate delivery so we need to handle scheduler)
> Schedule sending with sidekiq

Mandrill  has parameter send_at, when this message should be sent as a UTC timestamp in YYYY-MM-DD HH:MM:SS format. If you specify a time in the past, the message will be sent immediately. An additional fee applies for scheduled email, and this feature is only available to accounts with a positive balance.
I guess own scheduler is excess

**Comment by olimart** [comment] 2015-02-23 12:00
We need our own because fees apply. However this is less urgent so we can
keep for later.

Le lundi 23 février 2015, Gennady <notifications@github.com> a écrit :

> Ability to schedule sending at a future date (Mandrill only support
> immediate delivery so we need to handle scheduler)
> Schedule sending with sidekiq
>
> Mandrill has parameter send_at, when this message should be sent as a UTC
> timestamp in YYYY-MM-DD HH:MM:SS format. If you specify a time in the past,
> the message will be sent immediately. An additional fee applies for
> scheduled email, and this feature is only available to accounts with a
> positive balance.
> I guess own scheduler is excess
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/yamail/issues/1#issuecomment-75522330>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Blog <http://blog.yafoy.com> | Joli Bento <https://jolibento.com> | Les
Bonbecs <https://lesbonbecs.com/> | Logcamp <https://log.camp> | Formtastic
<https://formz.herokuapp.com>

**Comment by croko** [comment] 2015-02-23 12:29
> Send email campaigns

is campaign associated with service provider?

**Comment by olimart** [comment] 2015-02-23 13:14
yes

**Comment by croko** [comment] 2015-02-23 13:22
is there no model of the recipients?

**Comment by olimart** [comment] 2015-02-23 13:30
recipients = whoever is part of the list at the moment where campaign is sent.

**Comment by croko** [comment] 2015-02-23 13:32
there only name in list model, looks like we need associated table for emails

**Comment by olimart** [comment] 2015-02-23 13:33
Either save all in list model else new model.

**Comment by olimart** [comment] 2015-02-23 13:35
You can add more fields to list model. I think if you try the import process on Mailchimp you will need a better understanding on how lists are used and how we need to save emails info (and other info.).

**Comment by croko** [comment] 2015-02-23 13:35
separated table for emails is better for performance and management

**Comment by croko** [comment] 2015-02-23 13:42
https://mandrillapp.com/api/docs/messages.ruby.html#method=send-template
please mark important parameters from Parameters table. I guess we should add them to List model

**Comment by olimart** [comment] 2015-02-23 13:58
the very minimum to be able to send out emails like subject, from, Google Analytics, To, track_opens, track_clicks.
We can always add other params later. It should go to campaigns model (just like mail chimp does it when you create a new campaign).

**Comment by croko** [comment] 2015-02-24 16:18
What email templates do you mean - own or Mailchimp?

**Comment by croko** [comment] 2015-02-24 16:37
> After campaign sent we need to take screenshot of email

what you mean screenshot of email?
 
> Need to capture campaign status from provider:
> Campaign scheduled/sent/canceled...

Campaign sends emails one time or repeat?

> Need to capture basic info about campaign:
> 100 sent, 3, bounced back...

we should store this?

**Comment by croko** [comment] 2015-02-24 16:41
is api key one for whole app or every campaign (and user?) should have own key?

**Comment by croko** [comment] 2015-02-24 16:46
> Need to capture campaign status from provider:
> Campaign scheduled/sent/canceled...

we can't create campaign via API, we can only track every email status

**Comment by olimart** [comment] 2015-02-24 16:55
> we can't create campaign via API, we can only track every email status

Yes I know. Campaigns are internal.

> is api key one for whole app or every campaign (and user?) should have own key?

Per user

> What you mean screenshot of email?

I mean image of campaign rendering (leave for later)

> Campaign sends emails one time or repeat?

Campaign is unique. If you want to repeat then you create a new campaign.

> we should store this?

Yes or no. Else we query Mandrill API.

**Comment by croko** [comment] 2015-02-25 14:36
tell me more about templates and screenshot please. Use liquid for templates?

**Comment by olimart** [comment] 2015-02-25 17:12
Re: template, liquid is fine. Basically, it's just copy&paste, no validations. It's not really template but message content for the campaign. User will take care of content separately, we only store message to send. In other words we only focus on sending not email message generation.

Re: screenshot, the idea is when you access the campaign (show page for example) (and assuming message not nil) we'll render message content as HTML. It will be easier for the user to remember what that email looked like (instead of viewing code). Render with merging list first record

**Comment by croko** [comment] 2015-02-27 13:34
Please take a look Templates, Which variables user can pass to template? And how they should be defined?

**Comment by croko** [comment] 2015-02-27 13:35
> Render with merging list first record

like templates#show?

**Comment by olimart** [comment] 2015-02-27 15:12
Not good at all.
We don't need email_template model. We need to send out email.

To send email blast, user creates campaign. In campaign model, there is field for email_message, where user copy/paste email template (using liquid for variables).

> Please take a look Templates, Which variables user can pass to template? And how they should be defined?

The first step is to import lists. Like I said, variables depend on the list.
Did you sign up to Maiclhimp? Did you check out the import? Did you look at their campaign creation process?

**Comment by croko** [comment] 2015-02-28 16:51
> Did you sign up to Maiclhimp?

yes

> Did you check out the import?

not yet, I did not know that this is so important.

WBR,
    Gennady Kudelya

**Comment by croko** [comment] 2015-03-02 14:05
I explored Maiclhimp and there a list of predefined templates and user's template. This corresponding with Template.model. Template not depend on list only on fields name.
P.S.
Do you want to clone Maiclhimp?

**Comment by olimart** [comment] 2015-03-02 14:12
I don’t want to clone Mailchimp.

I asked you to look at the import process, so you can see:
a. how it works
b. how to deal with dynamic lists (we can not predict information sent to
those lists)
c. See how lists segments work
d. How to manage lists

Once done. We take those lists to send them email campaigns. To send an
email campaign, we need content (email body). But we half follow Mailchimp
process. Start is similar, since we create a new campaign and ask for a
bunch of info such as from, email object, and email content (we do not deal
with email content editing, just plain copy/paste. Email content might have
dynamic values, hence liquid tempting engine, to merge with email list).

Does that make sense?

**Comment by croko** [comment] 2015-03-02 14:13
ok, I leave template and switch to lists

**Comment by croko** [comment] 2015-03-04 14:40
Take a look list members import. Sample files in fixtures directory

**Comment by olimart** [comment] 2015-03-04 15:14
- Need to validate csv file before import (raising an exception)
- Need to ensure people can not submit if no file selected first
- Need to make sure it works with `;` symbol as well
- When you import it should add to the list and not replace existing data
- API key should live under user and not by campaign
- Looks like you're assuming that the first column includes email address (after import headers are wrong)
  - I can live with that but we need to specify first column = email
- Open PR when you want me to review

**Comment by croko** [comment] 2015-03-04 15:16
> Looks like you're assuming that the first column includes email address (after import headers are wrong)

email field detects by "@" sign

**Comment by croko** [comment] 2015-03-04 15:17
> Need to ensure people can not submit if no file selected first

csv submitted from list's show, so list exists

**Comment by croko** [comment] 2015-03-04 15:19
> Need to make sure it works with ; symbol as well

we could add dropdown for selecting column separator or detect from file

**Comment by croko** [comment] 2015-03-04 15:20
> API key should live under user and not by campaign

Could one user use different providers for different campaigns?

**Comment by olimart** [comment] 2015-03-04 15:21
> email field detects by "@" sign

great. but check this out.
![capture d ecran 2015-03-04 a 10 18 51]
(https://cloud.githubusercontent.com/assets/547754/6486304/fb5fb756-c257-11e4-807c-0762a8769e6b.png)

> we could add dropdown for selecting column separator or detect from file

detect from file

> csv submitted from list's show, so list exists

Import button becomes active if file selected.

**Comment by olimart** [comment] 2015-03-04 15:24
> Could one user use different providers for different campaigns?

yes, but in this case user will select provider (not key). The risk with saving key with campaign is if key is revoked or no longer in use, we have it all over the map. Same if we want to clone the campaign later on. We should take the latest key available from user's account and send.

**Comment by croko** [comment] 2015-03-04 15:30
> great. but check this out.

which file you imported?

**Comment by olimart** [comment] 2015-03-04 15:36
`list_members_without_headers.csv`

**Comment by croko** [comment] 2015-03-05 12:28
Do we need "skip columns" functionality for import?

**Comment by olimart** [comment] 2015-03-05 14:39
no let's assume that file is ready to be imported. But we may need the 'rename column' function (does not have to be as fancy as Mailchimp though).

**Comment by croko** [comment] 2015-03-05 15:46
Segments should be exactly like segments in Mailchimp?

**Comment by olimart** [comment] 2015-03-05 15:50
yes. but if too complex let's talk.
I don't want to make filters too complex.

**Comment by croko** [comment] 2015-03-05 15:51
describe minimal functional please

**Comment by olimart** [comment] 2015-03-05 17:08
- Segments are dynamic
  - If I add new record and matches segments condition then it should automatically be part of segment
- Check against perfect match. For example, if location column holds 'Aa', 'Bb, 'Cc' then we can search for perfect match MyText == 'Aa'
- AND clause between multiple rules. Let's say maximum of 3 clauses per segment.
- Maybe Ransack gem can help with the clause.
- Maybe checkbox to manually add records to segment

**Comment by croko** [comment] 2015-03-13 09:31
Which features of this https://us10.admin.mailchimp.com/lists/settings/merge-tags do we need?

**Comment by olimart** [comment] 2015-03-13 12:49
- Ability to rename column header
- Ability to name merge tag (by default system will assign sequential number)

- Rules:
  - At least one column must be named email
  - Merge tag must be unique

![capture d ecran 2015-03-13 a 08 43 43](https://cloud.githubusercontent.com/assets/547754/6638558/ad7d25d4-c95d-11e4-8566-a4267af09e34.png)

**Comment by croko** [comment] 2015-03-13 15:51
do we need field type?

**Comment by olimart** [comment] 2015-03-13 15:52
no (unless it helps with segment rules greater than...)

**Comment by croko** [comment] 2015-03-13 15:55
do we need list members management? Remove, batch remove, manual add from form?

**Comment by croko** [comment] 2015-03-13 15:57
And could you write minimal spec for templates? Mailchimp has rich list of features, I don't know if we need all of them

**Comment by olimart** [comment] 2015-03-13 15:59
- Individual remove 
- clear the whole list
- update, will be done through re-import (once existing records are overriden instead of imported twice)

no spec for templates. it's just plain html with merge tags.

**Comment by croko** [comment] 2015-03-19 18:02
Mandrill API not identical Mailchimp features. It has hardcoding field "Name" in message API.
to": [
            {
                "email": "recipient.email@example.com",
                "name": "Recipient Name",
                "type": "to"
            }
        ],
so I guess we need to have this field hardcoding too (like email). Or mark this field as name, assign it liquid tag and use it in API.

**Comment by olimart** [comment] 2015-03-19 18:05
is Name field required ?

**Comment by croko** [comment] 2015-03-19 18:28
no, it's optional (he optional display name to use for the recipient)

**Comment by croko** [comment] 2015-03-19 18:45
Mailchimp use separate field for name 
![screen shot 2015-03-19 at 20 43 44](https://cloud.githubusercontent.com/assets/333912/6738143/b4cc5a92-ce78-11e4-9faf-fb0b14ac169b.png)

**Comment by olimart** [comment] 2015-03-19 18:48
the problem I see is if we have full_name, first_name, or name columns.
On campaign form, we could choose which column to use for name.

**Comment by croko** [comment] 2015-03-19 18:55
so I'll add it to campaign form

**Comment by croko** [comment] 2015-03-20 12:54
> update, will be done through re-import (once existing records are overriden instead of imported twice)

I have no idea how update via reimport. Any field may be changed, how find which member was changed? May be on update delete all existing members and import again from file?

**Comment by olimart** [comment] 2015-03-20 13:18
based on email field. 
Here is an example to update existing records (based on id, but for us it's email field)
http://railscasts.com/episodes/396-importing-csv-and-excel

**Comment by croko** [comment] 2015-03-20 13:45
I know how realize, but was not sure about criteria

**Comment by croko** [comment] 2015-03-20 16:17
we have a pb with update. Keys in list should be == keys from file. But user can change keys (column headers) and they may be different from file...

**Comment by croko** [comment] 2015-03-20 17:13
looks like all tasks are completed, except updating list members

**Comment by olimart** [comment] 2015-03-20 17:24
> we have a pb with update. Keys in list should be == keys from file. But user can change keys (column headers) and they may be different from file...

can't we have our own set of keys ID

> looks like all tasks are completed, except updating list members

So it' sending campaigns? Submit PR

**Comment by croko** [comment] 2015-03-20 17:29
I tested with test key, in this mode emails do not send to recepients

**Comment by croko** [comment] 2015-03-20 17:29
> can't we have our own set of keys ID

no, list is array os hashes

**Comment by croko** [comment] 2015-03-20 19:38
are you really prefer multiline instead of one long line?

**Comment by olimart** [comment] 2015-03-20 19:49
> are you really prefer multiline instead of one long line?

where ?

**Comment by croko** [comment] 2015-03-20 20:46
in robocop alerts.

**Comment by olimart** [comment] 2015-04-04 03:28
Do you actually receive emails when sending out campaign?
I can see in Mandrill that they are sent but nothing in my Gmail.

**Comment by croko** [comment] 2015-04-04 05:07
I used api key for testing. With this key Mandrill emulate process without real sending. You should change key for real sending.

**Comment by olimart** [comment] 2015-04-27 22:50
ok so I can confirm that email are blank and not sent/delivered.

Could be due to #8 the `liquidize` method since contant and subject remain blank. When I inspect on Mandrill, content is empty.

**Comment by croko** [comment] 2015-04-28 12:22
I tested with real api key and email and didn't receive email, but in mandrill logs email marked as sent.

Method: messages/send.json
Time: Apr 28, 2015 3:14 pm
Call time: 1.01s
IP: 91.203.61.36
User Agent: excon/0.44.2
Full Request
{
    "message": {
        "subject": "Commodi accusamus officiis dolorem optio.",
        "from_email": "jerad_konopelski@rippin.biz",
        "from_name": "Devonte Shields",
        "track_opens": true,
        "track_clicks": true,
        "google_analytics_campaign": [
            "[\"message.from_email@example.com\"]"
        ],
        "to": [
            {
                "name": "",
                "type": "to",
                "email": "crokogk@gmail.com"
            }
        ],
        "html": "<p>Dear Victoria Block,</p>\n              <p></p>\n              <p>This is to confirm that your account is now active.</p>\n              <p></p>\n              <p>Thank you,</p>\n              <p>Victoria Block</p>"
    },
    "async": false,
    "ip_pool": null,
    "send_at": null,
    "key": "tt8drAjJZE-KH8HZCTxndg"
}
Full Response
[
    {
        "email": "crokogk@gmail.com",
        "status": "sent",
        "_id": "6545a7bb2d474be8b1ba51aea88f1aff",
        "reject_reason": null
    }
]

**Comment by croko** [comment] 2015-04-28 12:24
did you check logs in https://mandrillapp.com/settings/api ?

**Comment by olimart** [comment] 2015-05-07 03:18
back to previous issue. Preview remains empty. Issue with liquid method after file import.

**Comment by croko** [comment] 2015-05-08 16:16
forks for me... Can't reproduce

**Closed** 2015-05-09 21:33 UTC
Labels: P1
